import "./globals.css";
import ToastProvider from "@/components/ToastComponent";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToastProvider>{children}</ToastProvider>
      </body>

      {/* <Toaster /> */}
    </html>
  );
}
