import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-400">
      <body className={poppins.className}>
        {/* <ToastProvider></ToastProvider> */}
        <div className={`max-w-[3500px] mx-auto relative`}>{children}</div>
        <Toaster
          toastOptions={{
            duration: 5000,
            style: {
              padding: "0",
              borderRadius: "0",
              margin: "0",
              gap: "0",
              top: "0",
              right: "0",
              bottom: "0",
              left: "0",
              boxShadow: "none",
              background: "transparent",
            },
          }}
        />
      </body>
    </html>
  );
}
