export const AUTH_ROUTES = {
  signIn: '/auth/sign-in',
  signup: '/auth/sign-up',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset',
  createNewPassword: '/auth/create-new-password',
  verification: '/auth/verification',
  confirmAccount: '/auth/confirm-account',
} as const;

export const APP_ROUTES = {
  home: '/',
  dashboard: '/dashboard',
  vendors: '/vendors',
  customers: '/customers',
  products: '/products',
  productsCloth: '/products/clothing',
  productsAccessories: '/products/accessories',
  productsFabrics: '/products/fabrics',
  productsAdd: '/products/add-product',
  staticPage: '/static-page',
  marketing: '/marketing',
  admin: '/admin',
  payment: '/payment',
  notifications: '/notifications',
  performance: '/performance',
  support: '/support',
  settings: '/settings',
  feedback: '/feedback',
  help: '/help',
  orders: '/orders',
  wallet: '/wallet',
  notification: '/notification',
  add: '/add',
  details: '/details',
  productDetails: '/product-details',
} as const;
